# Generated by Django 4.2.3 on 2023-08-31 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anime', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sound',
            name='sound',
            field=models.FileField(upload_to='Sounds'),
        ),
    ]
