# Generated by Django 4.1.11 on 2023-09-06 06:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('anime', '0002_alter_sound_sound'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='user',
        ),
        migrations.RemoveField(
            model_name='sound',
            name='project',
        ),
        migrations.DeleteModel(
            name='Image',
        ),
        migrations.DeleteModel(
            name='Project',
        ),
        migrations.DeleteModel(
            name='Sound',
        ),
    ]
