# Generated by Django 4.1.11 on 2023-09-06 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('anime', '0004_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='user',
            new_name='author',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='title',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='project',
            name='description',
        ),
    ]
