# Generated by Django 4.2.3 on 2023-09-08 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('anime', '0005_rename_user_project_author_rename_title_project_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='image_id',
            new_name='image_name',
        ),
        migrations.RenameField(
            model_name='sound',
            old_name='sound_id',
            new_name='sound_name',
        ),
    ]
